### ISSUE TITLE
Add Acrylic and Blur Effect

### ISSUE THREAD

**Issue by ibandim123** [Steamforge/codex-effect-vscode#10]
Hi, everything alright?

I like very much this theme! Do you can add acrylic and blur effect for him?

**Comment by Steamforge** [comment]
Hi @ibandim123 

Can you please clarify what you are asking?

**Comment by ibandim123** [comment]
How i used: 
![image](https://github.com/Steamforge/codex-effect-vscode/assets/59544620/2b53124c-2a0b-438c-ad4d-9242b148ce63)

I talk about that: 
![image](https://github.com/Steamforge/codex-effect-vscode/assets/59544620/76ca26aa-7550-461a-a177-f3e3bcbec8bc)

**Comment by Steamforge** [comment]
@ibandim123 what you're asking about is a wallpaper/background image. VSCode does not seem to support this in a theme but there are extensions which can help.

VSCode feature request for images in themes: https://github.com/microsoft/vscode/issues/84120

VSCode extensions to add background images:
https://marketplace.visualstudio.com/items?itemName=katsute.code-background
https://marketplace.visualstudio.com/items?itemName=shalldie.background
